# Generated by Django 5.1.3 on 2024-12-02 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/profile_pictures/channels/",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True, related_name="channels", to="accounts.account"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Bot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/profile_pictures/bots/"
                    ),
                ),
                ("username", models.CharField(max_length=100, null=True, unique=True)),
                ("token", models.CharField(max_length=100, unique=True)),
                ("is_running", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "required_pay_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.account",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True, related_name="bots", to="accounts.account"
                    ),
                ),
                (
                    "channel",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bot",
                        to="core.channel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Pay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("UZS", "Uzs"),
                            ("USD", "Usd"),
                            ("EUR", "Eur"),
                            ("RUB", "Rub"),
                            ("TON", "Ton"),
                            ("T_STAR", "T Star"),
                        ],
                        default="UZS",
                        max_length=6,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_payed", models.BooleanField(default=False)),
                ("payed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.bot",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
